import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :epe, EPEWeb.Endpoint,
  url: [host: "epe-app.fly.dev", port: 80]

config :logger, level: :info

# inet6 required for fly.io
config :edgedb,
  tcp: [:inet6],
  pool_size: 10,
  database: "epe_prod"
